# Generated by Django 5.0.1 on 2024-01-20 12:00

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    """
    Cria um superusuário a partir de variáveis de ambiente.
    """
    User = apps.get_model('auth', 'User')

    username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    if not all([username, email, password]):
        print("Variáveis de ambiente para superusuário não definidas. Pulando criação.")
        return

    if User.objects.filter(username=username).exists():
        print(f"Superusuário com username '{username}' já existe. Pulando criação.")
    else:
        print(f"Criando superusuário '{username}'...")
        User.objects.create_superuser(username=username, email=email, password=password)
        print("Superusuário criado com sucesso.")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'), # Garante que as tabelas do app já existem
        ('auth', '0012_alter_user_first_name_max_length'), # Dependência do modelo User
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
